const NUMBER_OF_CELLS = 81;
const ROW_LENGTH = Math.ceil(Math.sqrt(NUMBER_OF_CELLS)); // 9
const SECTION_LENGTH = Math.ceil(Math.sqrt(ROW_LENGTH)); // 3
const DELIMITER = '-';
const CELL_NAME_TEMPLATE = 'c';
const OPTION_NAME_TEMPLATE = 'o';
const SELECT_NAME_TEMPLATE = 's';

export { NUMBER_OF_CELLS, ROW_LENGTH, SECTION_LENGTH, DELIMITER, CELL_NAME_TEMPLATE, OPTION_NAME_TEMPLATE, SELECT_NAME_TEMPLATE };